# Generated by Django 3.2.16 on 2023-01-23 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_body', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='comments_co_post_id_380fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='comments_co_created_5f6a12_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['owner', 'created_at'], name='comments_co_owner_i_86b627_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['owner', 'post', 'created_at'], name='comments_co_owner_i_c80390_idx'),
        ),
    ]
